# Generated by Django 4.1 on 2024-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_userextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='links',
            field=models.URLField(blank=True),
        ),
    ]
